nginx:
  container_name: nginx
  build: ./.docker/nginx
  environment: 
    NGINX_SERVER_NAME: '${SERVER_NAME}.com'
    LETSENCRYPT: 'true'
  volumes:
    - ./.docker/nginx/default.crt:/srv/config/fullchain.pem
    - ./.docker/nginx/default.key:/srv/config/privkey.pem
    - ./.docker/nginx/access.log:/var/log/nginx/${SERVER_NAME}.com.default.log
    - ./.docker/nginx/error.log:/var/log/nginx/${SERVER_NAME}.com.error.log
    - /etc/hosts:/etc/hosts
  volumes_from: 
    - letsencrypt
    - php
  ports:
    - '80:80'
    - '443:443'
  extra_hosts:
    - "app.192.168.33.10.nip.io:127.0.0.1"
    - "manage.192.168.33.10.nip.io:127.0.0.1"

php:
  build: ./.docker/php
  volumes:
    - /php
    - .:/srv/www
    - /run/mysqld
    - ./.docker/php/php.log:/var/log/php.log
    - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./.docker/php/locale:/etc/default/locale
  volumes_from:
    - mysql-data
  working_dir: /srv/www
  links:
    - mysql

mysql:
  container_name: mysql
  build: ./.docker/mysql
  # image: mariadb:latest
  environment:
    MYSQL_ROOT_PASSWORD: '${SERVER_NAME}'
    MYSQL_DATABASE: '${SERVER_NAME}'
    MYSQL_USER: '${SERVER_NAME}'
    MYSQL_PASSWORD: '${SERVER_NAME}'
  expose: 
    - '3306'
  volumes_from:
    - mysql-data
  volumes:
    - /run/mysqld
    - .:/srv/www
    - ./.docker/mysql/initdb.d/:/docker-entrypoint-initdb.d/
    - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - '3306:3306'

mysql-data:
  image: busybox
  volumes:
    - ./.docker/persistent/mysql:/var/lib/mysql

# pydio-data:
#   image: busybox
#   volumes:
#     - ./persistent/data:/pydio-data

letsencrypt:
  container_name: letsencrypt
  build: ./.docker/letsencrypt
  volumes:
      - ./.docker/persistent/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt
      - /srv/letsencrypt-webrootauth
  command: root certonly --email ${SERVER_NAME}@gmail.com -d ${SERVER_NAME}.com -d www.${SERVER_NAME}.com --renew-by-default -a webroot --webroot-path /srv/letsencrypt-webrootauth --text --agree-tos --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory
